#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 13 13:41:50 2023

@author: bob
"""

import torch
import clip
from PIL import Image

class Iclip():
    
    def __init__(self):
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model, self.preprocess = clip.load("ViT-B/32", device=self.device)
        
    
    def input(self, I_path, T):
        image = self.preprocess(Image.open(I_path)).unsqueeze(0).to(self.device)
        text = clip.tokenize(T).to(self.device)
        
        with torch.no_grad():
            image_features = self.model.encode_image(image)
            text_features = self.model.encode_text(text)
            
            logits_per_image, logits_per_text = model(image, text)
            probs = logits_per_image.softmax(dim=-1).cpu().numpy()
        
        print("Label probs:", probs)
        
        return probs


